set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"
" Plugin 'tpope/vim-fugitive'
"
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"
" Plugin 'git://git.wincent.com/command-t.git'
" 
" git repos on your local machine (i.e. when working on your own plugin)
"
" Plugin 'file:///home/gmarik/path/to/plugin'
"
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
"
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'scrooloose/nerdtree'
Plugin 'flazz/vim-colorschemes'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


"Mapping arrow keys to echo do not use in all modes
nnoremap <Up> :echo "Dont't use this!"<CR>
vnoremap <Up> :<C-u>echo "Dont't use this!"<CR>
inoremap <Up> <C-o>:echo "Dont't use this!"<CR>

nnoremap <Down> :echo "Dont't use this!"<CR>
vnoremap <Down> :<C-u>echo "Dont't use this!"<CR>
inoremap <Down> <C-o>:echo "Dont't use this!"<CR>

nnoremap <Left> :echo "Dont't use this!"<CR>
vnoremap <Left> :<C-u>echo "Dont't use this!"<CR>
inoremap <Left> <C-o>:echo "Dont't use this!"<CR>

nnoremap <Right> :echo "Dont't use this!"<CR>
vnoremap <Right> :<C-u>echo "Dont't use this!"<CR>
inoremap <Right> <C-o>:echo "Dont't use this!"<CR>


" Turning of compatiability with older VI
set nocompatible

" finding files
" This recursivly looks for files
" Tab completion for file look
set path+=**

" Turns on numbers on right side on, to turn off type 'set nonumber'
set number

" enabales syntax highlighting
syntax enable

" Set auto indenting on
set ai

" Display all matching files when we tab complete
set wildmenu

" Theme solaraized for airline powerbar
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'

" Using Molokai color scheme
colorscheme Molokai
